### PR TITLE
Improve documentation with explanation

### PR DESCRIPTION
**Pull request by Astronaut-Wolowitz**
Please do it asap

### CODE REVIEW

**Review by rkat7 — COMMENTED** [review]
I think it's better to link the documentation of the respective models used. If it is a must to have the explanation then a one-liner would suffice.

**Review by rkat7 — CHANGES_REQUESTED** [review]
.

**Review by rkat7 — APPROVED** [review]
@Astronaut-Wolowitz Please add the explanations.

**Review by Astronaut-Wolowitz — COMMENTED** [review]
OKay. I'll see.

**Pull request merged**
